# Download Data
## FloodNet NYC Tutorial
Author: Mark Bauer

# Summary
TBD

# Import Libraries

In [50]:
# libraries
import requests
import polars as pl
import geopandas as gpd

In [51]:
libraries = {
    "requests": requests.__version__,
    "polars": pl.__version__,
    "geopandas": gpd.__version__,
}

for name, version in libraries.items():
    print(f"{name:10s} {version}")

requests   2.32.5
polars     1.38.1
geopandas  1.1.2

# FloodNet Catalog on NYC Open Data

[FloodNet Catalog Link](https://data.cityofnewyork.us/browse?Data-Collection_Data-Collection=FloodNet+NYC&sortBy=relevance&page=1&pageSize=20)

# Data Dictionary and Dataset Description

In [52]:
## dat dictionary
# url on NYC Open Data
url = "https://data.cityofnewyork.us/api/views/kb2e-tjy3/files/\
9acd9a23-79a2-4ac0-929a-b0fa02182db6?download=true&filename=Flood%20Events_Data%20Dictionary.xlsx"

# saved file name
local_file = "data/Flood Events_Data Dictionary.xlsx"

# download file
response = requests.get(url)
response.raise_for_status()
with open(local_file, "wb") as f:
    f.write(response.content)

## dataset description
# url on NYC Open Data
url = "https://data.cityofnewyork.us/api/views/kb2e-tjy3/files/\
266f25e5-1809-40a0-afd5-50fb69596ce1?download=true&filename=Floodnet_Open_Data_-_Data_Description_03.05.2026.pdf"

# saved file name
local_file = "data/Floodnet_Open_Data_-_Data_Description_03.05.2026.pdf"

# download file
response = requests.get(url)
response.raise_for_status()
with open(local_file, "wb") as f:
    f.write(response.content)

In [53]:
# sanity check
%ls data/

Flood Events_Data Dictionary.xlsx
Floodnet_Open_Data_-_Data_Description_03.05.2026.pdf
boroughs.parquet
flood-events.csv
metadata.csv

# Sensor Deployment Metadata

In [54]:
url = "https://data.cityofnewyork.us/resource/kb2e-tjy3.csv"
local_file = "data/metadata.csv"

# download file
response = requests.get(url)
response.raise_for_status()
with open(local_file, "wb") as f:
    f.write(response.content)

# sanity check file
metadata_df = pl.read_csv(local_file, try_parse_dates=True)

# inspect the shape of the data
n_rows, n_columns = metadata_df.shape
print("Metadata:")
print(f"Number of rows: {n_rows}")
print(f"Number of columns: {n_columns}")

Metadata:
Number of rows: 371
Number of columns: 16

In [55]:
# sanity check, preview data
metadata_df.head()

shape: (5, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sensor_na ┆ sensor_id ┆ date_inst ┆ tidally_i ┆ … ┆ latitude  ┆ longitude ┆ lowest_po ┆ location │
│ me        ┆ ---       ┆ alled     ┆ nfluenced ┆   ┆ ---       ┆ ---       ┆ int_heigh ┆ ---      │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ t_delta_i ┆ str      │
│ str       ┆           ┆ datetime[ ┆ str       ┆   ┆           ┆           ┆ nch…      ┆          │
│           ┆           ┆ μs]       ┆           ┆   ┆           ┆           ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ BK -      ┆ BK-junius ┆ 2023-05-2 ┆ No        ┆ … ┆ 40.668742 ┆ -73.90265 ┆ 13.43     ┆ POINT    │
│ Junius    ┆ -st-sutte ┆ 4         ┆           ┆   ┆           ┆ 8         ┆           ┆ (-73.902 │
│ St/Sutter ┆ r-ave-1dn ┆ 00:00:00  ┆           ┆   ┆           ┆           ┆           ┆ 658 40.6 │
│ Ave       ┆ f80       ┆           ┆           ┆   ┆           ┆           ┆           ┆ 68742)   │
│ BX - Metr ┆ BX-metrop ┆ 2025-09-2 ┆ No        ┆ … ┆ 40.840601 ┆ -73.85545 ┆ 8.78      ┆ POINT    │
│ opolitan  ┆ olitan-av ┆ 5         ┆           ┆   ┆           ┆ 9         ┆           ┆ (-73.855 │
│ Ave/Linde ┆ e-linden- ┆ 00:00:00  ┆           ┆   ┆           ┆           ┆           ┆ 459 40.8 │
│ n D…      ┆ dr-…      ┆           ┆           ┆   ┆           ┆           ┆           ┆ 40601)   │
│ Q - 147   ┆ Q-147-dri ┆ 2023-06-2 ┆ Yes       ┆ … ┆ 40.65572  ┆ -73.72955 ┆ 5.39      ┆ POINT    │
│ Drive/    ┆ ve-259-st ┆ 2         ┆           ┆   ┆           ┆ 8         ┆           ┆ (-73.729 │
│ 259 St    ┆ -1f5ig0   ┆ 00:00:00  ┆           ┆   ┆           ┆           ┆           ┆ 558 40.6 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5572)    │
│ M - E     ┆ M-e-122nd ┆ 2022-11-1 ┆ No        ┆ … ┆ 40.801601 ┆ -73.93748 ┆ 15.39     ┆ POINT    │
│ 122nd     ┆ -st-3rd-1 ┆ 3         ┆           ┆   ┆           ┆ 5         ┆           ┆ (-73.937 │
│ St/3rd    ┆ yjns0     ┆ 00:00:00  ┆           ┆   ┆           ┆           ┆           ┆ 485 40.8 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 01601)   │
│ BX -      ┆ BX-robert ┆ 2025-01-2 ┆ No        ┆ … ┆ 40.843944 ┆ -73.83972 ┆ 8.82      ┆ POINT    │
│ Waters    ┆ s-ave-wat ┆ 3         ┆           ┆   ┆           ┆ 8         ┆           ┆ (-73.839 │
│ Pl/ Fink  ┆ ers-pl-29 ┆ 00:00:00  ┆           ┆   ┆           ┆           ┆           ┆ 728 40.8 │
│ Ave       ┆ 21j…      ┆           ┆           ┆   ┆           ┆           ┆           ┆ 43944)   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Street Flooding Events Measured by FloodNet Sensors

In [56]:
# read in flood events as dataframe
max_limit = 500_000 # assign limit to large number
url = f"https://data.cityofnewyork.us/resource/aq7i-eu5q.csv?$limit={max_limit}"
local_file = "data/flood-events.csv"

# download file
response = requests.get(url)
response.raise_for_status()

with open(local_file, "wb") as f:
    f.write(response.content)

# sanity check
events_df = pl.read_csv(
    local_file,
    infer_schema_length=100000, # a few fiels have sparce data, so increase infer schema rows
    try_parse_dates=True # try to parse date fields
)

# inspect the shape of the data
n_rows, n_columns = events_df.shape
print("Flood Events:")
print(f"Number of rows: {n_rows}")
print(f"Number of columns: {n_columns}")

Flood Events:
Number of rows: 1887
Number of columns: 13

In [57]:
# sanity check, preview data
events_df.head()

shape: (5, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sensor_na ┆ sensor_id ┆ flood_sta ┆ flood_end ┆ … ┆ duration_ ┆ duration_ ┆ flood_pro ┆ flood_pr │
│ me        ┆ ---       ┆ rt_time   ┆ _time     ┆   ┆ above_12_ ┆ above_24_ ┆ file_dept ┆ ofile_ti │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ inches_mi ┆ inches_mi ┆ h_inches  ┆ me_secs  │
│ str       ┆           ┆ datetime[ ┆ datetime[ ┆   ┆ ns        ┆ ns        ┆ ---       ┆ ---      │
│           ┆           ┆ μs]       ┆ μs]       ┆   ┆ ---       ┆ ---       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Q - Beach ┆ Q-beach-8 ┆ 2023-10-3 ┆ 2023-10-3 ┆ … ┆ 103.6     ┆ 0.0       ┆ [0.00,    ┆ [0,      │
│ 84 St     ┆ 4-st-0me6 ┆ 0         ┆ 0         ┆   ┆           ┆           ┆ 0.87,     ┆ 1008,    │
│           ┆ 80        ┆ 12:00:39  ┆ 16:38:19  ┆   ┆           ┆           ┆ 1.02,     ┆ 1134,    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 1.38,     ┆ 1512,    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 1.93,…    ┆ 1826,    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 20…      │
│ BX - 1st  ┆ BX-1st-st ┆ 2025-04-2 ┆ 2025-04-2 ┆ … ┆ 0.0       ┆ 0.0       ┆ [0.00,    ┆ [0, 64,  │
│ St/Avenue ┆ -avenue-a ┆ 6         ┆ 7         ┆   ┆           ┆           ┆ 0.71,     ┆ 129,     │
│ A         ┆ -1zby90   ┆ 23:17:20  ┆ 11:55:34  ┆   ┆           ┆           ┆ 1.38,     ┆ 132,     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 1.38,     ┆ 196,     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 1.38,…    ┆ 260, 32… │
│ Q - Beach ┆ Q-beach-3 ┆ 2024-02-0 ┆ 2024-02-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ [0.00,    ┆ [0, 68,  │
│ 35        ┆ 5-st-beac ┆ 9         ┆ 9         ┆   ┆           ┆           ┆ 0.43,     ┆ 136,     │
│ St/Beach  ┆ h-channel ┆ 11:41:01  ┆ 13:20:57  ┆   ┆           ┆           ┆ 0.63,     ┆ 204,     │
│ Channel … ┆ -dr…      ┆           ┆           ┆   ┆           ┆           ┆ 0.71,     ┆ 273,     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0.94,…    ┆ 341, 40… │
│ BX -      ┆ BX-w-234t ┆ 2025-08-2 ┆ 2025-08-2 ┆ … ┆ 0.0       ┆ 0.0       ┆ [0.00,    ┆ [0, 60,  │
│ Tibbett   ┆ h-st-tibb ┆ 0         ┆ 1         ┆   ┆           ┆           ┆ 0.43,     ┆ 120,     │
│ Ave/W     ┆ ett-ave-2 ┆ 21:05:19  ┆ 00:46:19  ┆   ┆           ┆           ┆ 0.47,     ┆ 180,     │
│ 234th St  ┆ cak…      ┆           ┆           ┆   ┆           ┆           ┆ 0.47,     ┆ 240,     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0.51,…    ┆ 300, 36… │
│ Q -       ┆ Q-davenpo ┆ 2024-01-1 ┆ 2024-01-1 ┆ … ┆ 0.0       ┆ 0.0       ┆ [0.00,    ┆ [0, 63,  │
│ Davenport ┆ rt-ct-1-0 ┆ 0         ┆ 0         ┆   ┆           ┆           ┆ 0.47,     ┆ 127,     │
│ Ct 1      ┆ 7zks0     ┆ 00:39:25  ┆ 02:30:40  ┆   ┆           ┆           ┆ 0.47,     ┆ 189,     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0.43,     ┆ 252,     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0.43,…    ┆ 315, 37… │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Flood Sensor Locations

In [58]:
# read in NYC Boroughs geometries from NYC Open Data
path = "https://data.cityofnewyork.us/resource/gthc-hcne.geojson"
boro_gdf = gpd.read_file(path)

# preview data, confirm CRS
print(boro_gdf.crs)
boro_gdf.head()

EPSG:4326

,borocode,boroname,shape_area,shape_leng,geometry
0,5,Staten Island,1623618358.46,325912.288988,"MULTIPOLYGON (((-74.05051 40.56642, -74.05047 ..."
1,1,Manhattan,636631650.451,359537.866079,"MULTIPOLYGON (((-74.01093 40.68449, -74.01193 ..."
2,2,Bronx,1187199300.36,463147.071867,"MULTIPOLYGON (((-73.89681 40.79581, -73.89694 ..."
3,3,Brooklyn,1934462607.43,726953.044632,"MULTIPOLYGON (((-73.86327 40.58388, -73.86381 ..."
4,4,Queens,3041419178.99,887905.076018,"MULTIPOLYGON (((-73.82645 40.59053, -73.82642 ..."

In [59]:
# save locally
boro_gdf.to_parquet('data/boroughs.parquet')

In [60]:
# sanity check, list files
%ls data/

Flood Events_Data Dictionary.xlsx
Floodnet_Open_Data_-_Data_Description_03.05.2026.pdf
boroughs.parquet
flood-events.csv
metadata.csv